# Lines configured by zsh-newuser-install

source /home/raka/mnt/usefullscriptsetc/etc/zshrc
HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/raka/.zshrc'

autoload -Uz compinit
compinit
# End of lines added by compinstall
