# Lines configured by zsh-newuser-install


HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
bindkey -e
# End of lines configured by zsh-newuser-install
# The following lines were added by compinstall
zstyle :compinstall filename '/home/raka/.zshrc'

autoload -Uz compinit
compinit

if test -d ~/.oh-my-zsh; then 
	# Path to your oh-my-zsh instalation.
	  export ZSH=~/.oh-my-zsh/

	# Set name of the theme to load.
	# Look in ~/.oh-my-zsh/themes/
	# Optionally, if you set this to "random", it'll load a random theme each
	# time that oh-my-zsh is loaded.
	ZSH_THEME="honukai"

	# Uncomment the following line to use case-sensitive completion.
	# CASE_SENSITIVE="true"

	# Uncomment the following line to use hyphen-insensitive completion. Case
	# sensitive completion must be off. _ and - will be interchangeable.
	# HYPHEN_INSENSITIVE="true"

	# Uncomment the following line to disable bi-weekly auto-update checks.
	# DISABLE_AUTO_UPDATE="true"

	# Uncomment the following line to change how often to auto-update (in days).
	# export UPDATE_ZSH_DAYS=13

	# Uncomment the following line to disable colors in ls.
	# DISABLE_LS_COLORS="true"

	# Uncomment the following line to disable auto-setting terminal title.
	# DISABLE_AUTO_TITLE="true"

	# Uncomment the following line to enable command auto-correction.
	# ENABLE_CORRECTION="true"

	# Uncomment the following line to display red dots whilst waiting for completion.
	# COMPLETION_WAITING_DOTS="true"

	# Uncomment the following line if you want to disable marking untracked files
	# under VCS as dirty. This makes repository status check for large repositories
	# much, much faster.
	# DISABLE_UNTRACKED_FILES_DIRTY="true"

	# Uncomment the following line if you want to change the command execution time
	# stamp shown in the history command output.
	# The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
	# HIST_STAMPS="mm/dd/yyyy"

	# Would you like to use another custom folder than $ZSH/custom?
	# ZSH_CUSTOM=/path/to/new-custom-folder

	# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
	# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
	# Example format: plugins=(rails git textmate ruby lighthouse)
	# Add wisely, as too many plugins slow down shell startup.
	plugins=(git h z zsh-syntax-highlighting)
fi
# User configuration

export PATH="/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl:$HOME/bin:$HOME/mnt/bin"
# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='nvim'
# else
#   export EDITOR='nvim'
# fi

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# ssh
# export SSH_KEY_PATH="~/.ssh/dsa_id"

# Set personal aliases, overriding those provided by oh-my-zsh libs,
# plugins, and themes. Aliases can be placed here, though oh-my-zsh
# users are encouraged to define aliases within the ZSH_CUSTOM folder.
# For a full list of active aliases, run `alias`.
#
# Example aliases
# alias zshconfig="mate ~/.zshrc"
# alias ohmyzsh="mate ~/.oh-my-zsh"

test -f ~/.environment.rc -a -r ~/.environment.rc && . ~/.environment.rc
test -d ~/.oh-my-zsh && source ~/.oh-my-zsh/oh-my-zsh.sh

HISTSIZE=100

alias c='clear'
alias sp='dæmon spotify'
alias fr='dæmon firefox'
alias sshaway='ssh raka@84.27.33.98'
alias sshhome='ssh raka@192.168.0.101'
alias ts3='dæmon teamspeak3'
alias chr='dæmon chromium'
alias vi='vim'
alias zz='source ~/.zshrc' 
alias ..=cd\ .. ...=cd\ ../.. ....=cd\ ../../.. .....=cd\ ../../../.. +=pushd -=popd ++=pushd\;pushd
alias ls='COLUMNS="${COLUMNS}" LC_COLLATE=C /bin/ls' l=ls ll=ls\ -alisFg ltr='ls -ltr'
alias mvi=mv\ -i cpi=cp\ -i rmi=rm\ -i
alias dfh="df -h ." dush="du -sh"
psx() { ps x | grep "$1"; }  
alias uppaal='java -jar ~/Downloads/uppaal-4.0.14/uppaal.jar &'
alias i3configure='vim ~/.config/i3/config'
alias i3blocksconf='vim ~/i3blocks.conf'
alias df='df -h'
alias du="du -ach | sort -h"
alias free="free -mt"
alias psg="ps aux | grep -v grep | grep -i -e VSZ -e"
alias mkdir="mkdir -pv"
alias wget="wget -c"
alias histg="history | grep"
alias myip="curl http://ipecho.net/plain; echo"
alias y="yaourt"
alias yr="yaourt -Syuu"
alias eduroam="nmtui connect eduroam"


source /home/shared/usefullscriptsetc/etc/bash/quick-ssh
export EDITOR=/usr/bin/vim

#PS1='%{[0;1;36m%}[%*] %{[0;32m%}$USER %{[1;33m%}${PWD/#$HOME/~}%{[0;37;39m%}$(ys_hg_prompt_info)$(git_prompt_info)%{[1;31m%} \$ %{[0;37;39m%}'
PS1=' %{[1;33m%}${PWD/#$HOME/~}%{[0;37;39m%}$(ys_hg_prompt_info)$(git_prompt_info)%{[1;31m%} \$ %{[0;37;39m%}'




: <<EOF
%{[1m[34m%}#%{[00m%} %{[36m%}%n %{[37m%}at %{[32m%}antergosraka %{[37m%}in %{[1m[33m%}${PWD/#$HOME/~}%{[00m%}$(ys_hg_prompt_info)$(git_prompt_info) %{[37m%}[%*]
%{[1m[31m%}→ %{[00m%}
EOF

# End of lines added by compinstall
